version: '3'

services:
  # MariaDB Service
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smarthome
      MYSQL_USER: smarthome
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  # Angular Services
  angular_admin:
    build:
      context: ./
    container_name: angular_admin
    ports:
      - "4200:4200"
    expose:
      - 4200:4200
    volumes:
      - ./admin:/app
      - ./init.sh:/app/init.sh
    working_dir: /app/admin
    entrypoint: sh -c "/app/init.sh"

  angular_smarthome:
    build:
      context: ./
    container_name: angular_smarthome
    ports:
      - "4201:4200"
    volumes:
      - ./smarthome:/app
      - ./init.sh:/app/init.sh
    working_dir: /app/smarthome
    entrypoint: sh -c "/app/init.sh"

  angular_user:
    build:
      context: ./
    container_name: angular_user
    ports:
      - "4202:4200"
    volumes:
      - ./user:/app
      - ./init.sh:/app/init.sh
    working_dir: /app/user
    entrypoint: sh -c "/app/init.sh"

  # FastAPI Service
  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi
    volumes:
      - ./fastapi/app:/app
    ports:
      - "8000:8000"
      - 3000:3000
    entrypoint:
      [
        "uvicorn",
        "main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--log-config=log_conf.yml"
      ]
volumes:
  mariadb_data:
