"""change min max logic

Revision ID: a3fe72acae0a
Revises: 22422763fd24
Create Date: 2024-03-17 21:36:26.494619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3fe72acae0a'
down_revision: Union[str, None] = '22422763fd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjustvalue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adjust_value_action_id', sa.Integer(), nullable=True),
    sa.Column('metauielemeentvalue_id', sa.Integer(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adjust_value_action_id'], ['adjustvalueviewaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metauielemeentvalue_id'], ['metauielemeentvalue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adjustvalueviewaction', sa.Column('metauielement_id', sa.Integer(), nullable=True))
    op.drop_constraint('adjustvalueviewaction_ibfk_2', 'adjustvalueviewaction', type_='foreignkey')
    op.create_foreign_key(None, 'adjustvalueviewaction', 'metauielement', ['metauielement_id'], ['id'], ondelete='CASCADE')
    op.drop_column('adjustvalueviewaction', 'metauielemeentvalue_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adjustvalueviewaction', sa.Column('metauielemeentvalue_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'adjustvalueviewaction', type_='foreignkey')
    op.create_foreign_key('adjustvalueviewaction_ibfk_2', 'adjustvalueviewaction', 'metauielemeentvalue', ['metauielemeentvalue_id'], ['id'], ondelete='CASCADE')
    op.drop_column('adjustvalueviewaction', 'metauielement_id')
    op.drop_table('adjustvalue')
    # ### end Alembic commands ###
