"""init

Revision ID: b2d956fa6ba5
Revises: 
Create Date: 2024-02-19 22:35:06.853239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision  identifiers, used by Alembic.
revision: str = 'b2d956fa6ba5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptuirule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('actiongroup', sa.Enum('TASKCHANGE', 'LAYOUTCHANGE', 'SERVICE', name='actiongroupenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adaptuirule_level'), 'adaptuirule', ['level'], unique=False)
    op.create_table('smarthomedevice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.Enum('LAMP', 'HEATER', 'SHUTTER', name='iconenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adaptui_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['adaptui_id'], ['adaptuirule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smarthomedevicechannel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_no', sa.Integer(), nullable=True),
    sa.Column('smarthomedevice_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('INT', 'FLOAT', 'COLOR_RED', 'COLOR_GREEN', 'COLOR_BLUE', 'DIMMER', name='smarthomedevicechanneltypeenum'), nullable=True),
    sa.ForeignKeyConstraint(['smarthomedevice_id'], ['smarthomedevice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contextofuse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('INT', 'FLOAT', 'STRING', 'JSON', 'DEVICE', name='typeenum'), nullable=True),
    sa.Column('smarthomedevicechannel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smarthomedevicechannel_id'], ['smarthomedevicechannel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contextofuse_key'), 'contextofuse', ['key'], unique=False)
    op.create_index(op.f('ix_contextofuse_value'), 'contextofuse', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contextofuse_value'), table_name='contextofuse')
    op.drop_index(op.f('ix_contextofuse_key'), table_name='contextofuse')
    op.drop_table('contextofuse')
    op.drop_table('smarthomedevicechannel')
    op.drop_table('action')
    op.drop_table('smarthomedevice')
    op.drop_index(op.f('ix_adaptuirule_level'), table_name='adaptuirule')
    op.drop_table('adaptuirule')
    # ### end Alembic commands ###
